module.exports = {
  magicAxeBallAnswers: [
    'YES, AXE KILLS YOU!',
    'AXE-ACTLY!',
    'YOU MIGHT HAVE BEEN A FANCYMAN IN HEAVEN, BUT DOWN HERE YOU ARE NOTHING NEXT TO AXE!',
    'AXE THINKS SO!',
    'HAH HAH HAH!',
    'AS AXE SEES IT, YES!',
    'AXE THINKS IT\'S LIKELY!',
    'AXE HAS NO TIME FOR SUCH NONSENSE',
    'YES',
    'MY AXE POINTS TO **YES**',
    'AXE IS HAZY! TRY AGAIN!',
    'AXE ME THAT LATER!',
    'AXE CAN\'T TELL YOU THAT!',
    'WHEN THE TIME IS RIGHT!',
    'SHITTY WIZARD!',
    'YOU GET NOTHING!',
    'NO!',
    'NOT THIS TIME!',
    'YOU FOUGHT BADLY - DIED WORSE!',
    'CUT AND RUN!'
  ]
};